coverage:
  require_ci_to_pass: no
  notify:
    require_ci_to_pass: no
    wait_for_ci: no
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true